version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - ./app:/app
    ports:
      - 8000:5000
    environment:
      - FLASK_ENV=development
      - SECRET_API_KEY_DATAMALL=/run/secrets/api_key_datamall
    secrets:
      - api_key_datamall

secrets:
  api_key_datamall:
    file: ./secrets/api_key_datamall
